ListOfPrompts:
  - SpongeBob quitting his job at the Krusty Krab
  - Mario baking a cake with Princess Peach
  - Darth Vader hosting a BBQ party
  - The Avengers playing a game of cricket
  - Harry Potter and friends having a picnic in the Forbidden Forest
  - Batman and Robin washing the Batmobile
  - Homer Simpson competing in a donut-eating contest
  - Iron Man and Captain America having a dance-off
  - Yoda teaching a yoga class
  - The Scooby Gang having a beach party
  - Link from Zelda setting up a lemonade stand
  - Doctor Who trying to fix a broken TARDIS
  - Spider-Man hosting a knitting workshop
  - Thor struggling to assemble IKEA furniture
  - Winnie the Pooh and friends on a honey hunt
  - The Powerpuff Girls playing hide and seek
  - Gandalf setting off fireworks in the Shire
  - Mickey Mouse planting a magical garden
  - A Minion from Despicable Me trying to paint
  - The Flintstones hosting a rock 'n' roll party
  - The Ghostbusters playing laser tag with ghosts
  - Superman and Flash having a pizza-making competition
  - Alice in Wonderland having a tea party with Minecraft mobs
  - Pikachu and Ash playing electric guitar
  - The Teenage Mutant Ninja Turtles at a pizza festival
  - Sherlock Holmes solving a mystery in a Minecraft village
  - Indiana Jones searching for treasure in a jungle temple
  - The Joker and Harley Quinn hosting a comedy show
  - Wonder Woman leading a fitness boot camp
  - A Creeper trying to bake a cake without exploding
  - The Fellowship of the Ring playing a board game
  - Simba and friends organizing a Minecraft talent show
  - Deadpool hosting a cooking show
  - The Big Bang Theory gang having a LAN party
  - A Villager trying to trade with Star Wars droids
  - Optimus Prime and Bumblebee in a car race
  - Captain Jack Sparrow searching for hidden treasure in an ocean biome
  - Frodo and Sam cooking a giant Minecraft fish
  - Elon Musk launching a rocket in Minecraft
  - A Minecraft Steve doing a fashion show with Enderman
  - Minecraft Alex running a farm with animated movie animals
  - The Friends cast building a replica of Central Perk in Minecraft
  - The Avengers building their own Minecraft city
  - Elsa from Frozen creating an ice palace in a snow biome
  - Dumbledore hosting a Minecraft wizardry class
  - The Guardians of the Galaxy having a dance party in the Nether
  - A Stormtrooper trying to ride a horse
  - The Terminator trying to plant a garden
  - James Bond on a spy mission in a village
  - Tony Stark inventing new redstone contraptions
  - The Justice League having a swimming race
  - A group of Villagers reenacting a scene from Game of Thrones
  - The Simpsons family building their house in Minecraft
  - A zombie horde trying to start a band
  - The cast of Friends going on a minecart adventure
  - Wolverine trying to shear sheep without harming them
  - An Ender Dragon trying to bake cookies
  - Jon Snow teaching Villagers how to fight
  - The Mad Hatter hosting a crazy hat contest
  - Minecraft Steve and Alex on a treasure hunt
  - A Creeper and a Zombie having a dance battle
  - Sonic the Hedgehog racing against a minecart
  - A Witch brewing love potions for Villagers
  - The cast of Stranger Things exploring an abandoned mineshaft
  - Willy Wonka opening a candy store in a village
  - The Ghostbusters trying to capture a Ghast
  - King Kong climbing a Minecraft jungle tree
  - Voldemort and Harry Potter having a spell duel
  - The Little Mermaid exploring an ocean monument
  - Beetlejuice hosting a prank show in a haunted village
  - Goku from Dragon Ball training Villagers
  - Katniss Everdeen teaching archery to Minecraft players
  - The Genie from Aladdin granting wishes in Minecraft
  - A Zombie Pigman trying to lead a choir